require: rubocop-rails

AllCops:
    Exclude:
        - 'pong/db/schema.rb'

Style/FrozenStringLiteralComment:
        Enabled: false

Style/StringLiterals:
        Enabled: false

Style/Documentation:
        Enabled: false

Rails/FilePath:
        Enabled: false
