require: rubocop-rails

AllCops:
    Exclude:
        - 'db/schema.rb'

Style/FrozenStringLiteralComment:
    Enabled: false

Style/StringLiterals:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Style/RegexpLiteral:
    Exclude:
        - 'app/uploaders/user_image_uploader.rb'

Rails/FilePath:
    Enabled: false

Metrics/MethodLength:
    Exclude:
        - 'db/migrate/*.rb'

Metrics/ClassLength:
    Exclude:
        - 'test/**/*.rb'

Metrics/BlockLength:
    Exclude:
        - 'config/*.rb'
        - 'config/**/*.rb'

Naming/FileName:
    Exclude:
        - 'config/initializers/*.rb'

Rails/RedundantForeignKey:
    Exclude:
        - 'app/models/*.rb'
